### ISSUE TITLE
Adding extra language

### ISSUE THREAD

**Issue by kevinlefebure** [DanDiplo/Diplo.DictionaryEditor#4]
When adding an extra language in Umbraco, existing dictionary items do not show that language unless you save them one by one under settings/dictionary.
Is there an easy way to 'update' al items at once? Or even better, to show all existing languages immediately?

**Comment by DanDiplo** [comment]
Hi Kevin,

Unfortunately this is how Umbraco works and I can't change that. Umbraco only adds a new language once you save an existing dictionary item, so they don't exist until that point.

**Comment by kevinlefebure** [comment]
Hi,

Fixed my problem by executing this piece of code when language is added.

    private void updateDictionary()
    {
        var ls = ApplicationContext.Current.Services.LocalizationService;
        var allLanguages = ls.GetAllLanguages();
        foreach (IDictionaryItem item in ls.GetRootDictionaryItems())
        {
            foreach(var lang in allLanguages)
            {
                var translation = item.Translations.Where(x => x.LanguageId == lang.Id).FirstOrDefault();
                if(translation == null)
                {
                    var list = item.Translations.ToList();
                    list.Add(new DictionaryTranslation(lang, ""));
                    item.Translations = list;
                    ls.Save(item);
                }
            }
        }
    }

**Comment by DanDiplo** [comment]
Cool, good to know. I guess I could add something similar to my package that can be run on demand? I'll think about it. Though my next release will probably be a version for Umbraco 8 - but that's a while off!
